require:
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/LineLength:
  Exclude:
    - "spec/**/*.rb"

# Metrics/AbcSize:
#   Enabled: false

Metrics/BlockLength:
  Enabled: false
  # Exclude:
  #   - "*.gemspec"
  #   - "spec/**/*.rb"

Metrics/MethodLength:
  Max: 15

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/NumericLiterals:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/SymbolArray:
  EnforcedStyle: brackets
